[package]
name = "async_acme"
version = "0.1.0"
authors = ["conblem <ramonwehrli@gmail.com>"]
edition = "2018"

[[bin]]
name = "async_acme"
required-features = ["build-binary"]

[lib]
name = "async_acme"

[dependencies]
tokio = { version = "1.0", default-features = false }
reqwest = { version = "0.11", default-features = false, features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing = "0.1"
thiserror = "1"
base64 = "0.13"
bytes = "1.0"

ring = { version = "0.16", optional = true, default-features = false, features = ["std"] }

openssl = { version = "0.10", optional = true, default-features = false }

tracing-subscriber = { version = "0.2", optional = true }

[features]
default = ["ring", "reqwest/rustls-tls"]
native-tls = ["reqwest/default-tls", "openssl"]

build-binary = ["tokio/macros", "tokio/rt-multi-thread", "tracing-subscriber"]
# todo: figure out how to handle trust dns even needed?
# trust-dns = ["reqwest/trust-dns"]
