[package]
name = "mysql"
version = "0.1.0"
edition = "2018"

[dependencies]
testcontainers = "0.14"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
sqlx = { version = "0.6", features = ["runtime-tokio-rustls", "mysql"]}
